run:
  concurrency: 2
  timeout: 1m
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
  go: '1.22'

linters:
  enable-all: true
  disable:
    - deadcode # Deprecated
    - exhaustivestruct # Deprecated
    - golint # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - varcheck # Deprecated
