name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: build
      run: go build -v ./...

    - name: test
      run: go test -v ./...

  golangci:
    strategy:
      matrix:
        go: ['1.22']
    name: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
